#!/bin/bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT_NAME=`realpath $0`
FGLDEBDIR=`dirname $SCRIPT_NAME` 
#we recompile everything always: hence avoid version clashes
make -C $FGLDEBDIR clean_prog all > /dev/null
export FGLDEBDIR
export FGLRESOUREPATH=$FGLDEBDIR:$FGLRESOURPATH
export DBPATH=$FGLDEBDIR:$DBPATH
export FGLIMAGEPATH=$FGLDEBDIR:$FGLDEBDIR/icons:$FGLIMAGEPATH
#workaround the 3.00 weakness of adding image2font as soon as FGLIMAGEPATH is set
if [ -f "$FGLDIR/lib/image2font.txt" ] ; then
  export FGLIMAGEPATH=$FGLIMAGEPATH:"$FGLDIR/lib/image2font.txt"
fi
exec fglrun $FGLDEBDIR/fgldeb.42m "$@" 
